---
title: "Analyze Classification Changes"
---

## ***Periods***
```{r}
#| label: periods
# Climatological Reference Period
crp = "crp"
crp_beg <- 1961
crp_end <- 1990
crp_lbl <- paste("CRP ", crp_beg, "-", crp_end, sep = "")
# Recent Climate Period
rcp = "rcp"
rcp_beg <- 2015
rcp_end <- 2024
rcp_lbl <- paste("RCP ", rcp_beg, "-", rcp_end, sep = "")
```

## ***Packages***
```{r}
#| label: packages
suppressPackageStartupMessages({
  library(tidyverse)
  library(sf)
  library(arrow)
  library(units)
  library(gt)
  library(patchwork)
})
```

## ***Directories***
```{r}
#| label: directories
dir_rf <- "data/00_reference/"
dir_rd <- "data/04_classified_data/"
```

## ***Palettes***

```{r}
#| label: palettes

pth <- paste0(dir_rf,"ktc_group_palette.csv")
ktc_grp_palette_df<- read_csv(pth, show_col_types = FALSE)
ktc_grp_levels <- ktc_grp_palette_df$grp
ktc_grp_palette_str <- setNames(
  ktc_grp_palette_df$hex,
  ktc_grp_palette_df$grp
)

pth <- paste0(dir_rf,"ktc_type_palette.csv")
ktc_typ_palette_df <- read_csv(pth, show_col_types = FALSE)
ktc_typ_levels <- ktc_typ_palette_df$typ
ktc_typ_palette_str <- setNames(
  ktc_typ_palette_df$hex,
  ktc_typ_palette_df$typ
)

```


## ***Projections***
```{r}
#| label: projections
rbn_prj <- "ESRI:54030"
```

## ***Coastline***
```{r}
#| label: coastline
dir <- dir_rf
fil <- "global-coastline.gpkg"
pth <- paste(dir, fil, sep = "")
coastline_sf <- st_read(pth, quiet=TRUE)
```

## ***Import***
```{r}
#| label: import
pth <- paste(dir_rd, "ktc_grp_classification.gpkg", sep = "")
ktc_grp_sf <- st_read(pth, quiet=TRUE)

pth <- paste(dir_rd, "ktc_typ_classification.gpkg", sep = "")
ktc_typ_sf <- st_read(pth, quiet=TRUE)
```

## ***Functions***

### Calculate Group Changes

```{r}
#| label: fn_climate_group_changes
fn_climate_group_changes <- function(sf) {
  crp_grp_sf <- sf |>
    select(cgrp, mkm, pct, geom) |>
    summarize(
      mkm = sum(mkm),
      pct = sum(pct),
      geom = st_combine(geom),
      .by = c(cgrp)) |>
      rename(cg = cgrp)

  rcp_grp_sf <- sf |>
    select(rgrp, mkm, pct, geom) |>
    summarize(
      mkm = sum(mkm),
      pct = sum(pct),
      geom = st_combine(geom),
      .by = c(rgrp))|>
      rename(cg = rgrp)

  crp_grp_df <- crp_grp_sf |> st_drop_geometry()
  rcp_grp_df <- rcp_grp_sf |> st_drop_geometry()

  join_df <- crp_grp_df  |> 
    inner_join(rcp_grp_df, by = "cg") |>
    mutate(
      mkm.chg = mkm.y - mkm.x,
      pct.chg = pct.y - pct.x
    ) |>
    select(cg, mkm.x, mkm.y, mkm.chg, pct.x, pct.y, pct.chg)

  return(join_df)
}
```

### Build Group Changes Summary Table

```{r}
#| label: fn_build_summary_grp_table
fn_build_summary_grp_table <- function(df) {
  tbl <- df |>
    gt(rowname_col = "cg" ) |>
    tab_stubhead(label = "Group")|>
    tab_header(
      title = "Köppen-Trewartha Climate Group Changes",
    ) |>
    tab_spanner(
      label = "Area (Mkm²)",
      columns = c(mkm.x, mkm.y, mkm.chg)
    ) |>
    tab_spanner(
      label = "Group % of Total",
      columns = c(pct.x, pct.y, pct.chg)
    ) |>
    cols_label(
      cg = "Climate Group",
      mkm.x = "CRP",
      mkm.y = "RCP",
      mkm.chg = "Chg",
      pct.x = "CRP",
      pct.y = "RCP",
      pct.chg = "Chg"
    ) |>
    fmt_number(columns = c(mkm.x, mkm.y, mkm.chg), decimals = 1) |>
    fmt_number(columns = c(pct.x, pct.y, pct.chg), decimals = 2) |>
    grand_summary_rows(
      columns = c(mkm.x, mkm.y, mkm.chg, pct.x, pct.y, pct.chg),
      fns = list("Total" = ~ sum(.)),
      fmt = list(~ fmt_number(.x, decimals = 2))
    ) |>
    tab_footnote(
      footnote = paste("Climatological Reference Period ", crp_beg, "-", crp_end, sep = ""),
      locations = cells_column_labels(columns = c(mkm.x, pct.x))
    ) |>
    tab_footnote(
      footnote = paste("Recent Climate Period ", rcp_beg, "-", rcp_end, sep = ""),
      locations = cells_column_labels(columns = c(mkm.y, pct.y))
    ) |>
    tab_style(
      style = cell_fill(color = "lightblue"),
      locations = cells_body(
        rows = abs(pct.chg) > 1   # condition here
      )
    )
}
```

### Create Group Changes Map

```{r}
#| label: fn_create_grp_map
fn_create_grp_map <- function(plot_data, palette, cp) {

  p <- ggplot(plot_data) +
    geom_sf(aes(color = grp), size = 0.01) +
    scale_color_manual(values = palette, drop = FALSE) +
    geom_sf(data = coastline_sf, color = "black", linewidth = 0.1) +
    coord_sf(crs = rbn_prj) +
    guides(color = guide_legend(override.aes = list(size = 4 ))) # legend point size

  if (cp == "rcp") {
    p <- p +  
      labs(
        title = "Group Classification Changes ",
        color = "New\nGroup"
      )
  } else {
    p <- p + labs(color = "Old\nGroup")
  }

  return(p)
}
```

## ***Main Process***

```{r}
#| label: main_process

ktc_grp_sf <- ktc_grp_sf|>  mutate(cgrp = factor(cgrp, levels = ktc_grp_levels))
ktc_grp_sf <- ktc_grp_sf|>  mutate(rgrp = factor(rgrp, levels = ktc_grp_levels))

grp_chg_df <- fn_climate_group_changes(ktc_grp_sf)
grp_tbl_gt <- fn_build_summary_grp_table(grp_chg_df)
grp_tbl_gt

# typ_chg_df <- fn_climate_type_changes(ktc_sf)
# typ_tbl_gt <- fn_build_summary_table(typ_chg_df, "Trewartha")
# typ_tbl_gt

```

## ***Maps***

### All group changes

```{r}
#| label: map_all_changes
#| fig-height: 7
#| fig-aspect: .62   
#| out-width: 100%
 
v1_data <- ktc_grp_sf |>
  filter(cgrp != rgrp) |>
  select(rgrp) |>
  rename(grp = rgrp)
v1 <- fn_create_grp_map (v1_data, ktc_grp_palette_str, "rcp")

v2_data <- ktc_grp_sf |>
  filter(cgrp != rgrp) |>
  select(cgrp) |>
  rename(grp = cgrp)
v2 <- fn_create_grp_map (v2_data, ktc_grp_palette_str, "crp")

v1 / v2
```

### Group A Changes

```{r}
#| label: map_grp_A_changes
#| fig-height: 7
#| fig-aspect: .62  
#| out-width: 100%

plot_grp <- "A"

plot_data <- ktc_grp_sf |>
  filter(cgrp != rgrp) |>
  filter(rgrp == plot_grp) |>
  rename(grp = rgrp)
v3 <- fn_create_grp_map (plot_data, ktc_grp_palette_str, "rcp")

plot_data <- ktc_grp_sf |>
  filter(cgrp != rgrp) |>
  filter(rgrp == plot_grp) |>
  rename(grp = cgrp)
v4 <- fn_create_grp_map (plot_data, ktc_grp_palette_str, "crp")

v3 / v4
```

### Group B Changes

```{r}
#| label: map_grp_B_changes
#| fig-height: 7
#| fig-aspect: .62  
#| out-width: 100%

plot_grp <- "B"

plot_data <- ktc_grp_sf |>
  filter(cgrp != rgrp) |>
  filter(rgrp == plot_grp) |>
  rename(grp = rgrp)
v5 <- fn_create_grp_map (plot_data, ktc_grp_palette_str, "rcp")

plot_data <- ktc_grp_sf |>
  filter(cgrp != rgrp) |>
  filter(rgrp == plot_grp) |>
  rename(grp = cgrp)
v6 <- fn_create_grp_map (plot_data, ktc_grp_palette_str, "crp")

v5 / v6
```

```{r}

```