project:
  type: book
  output-dir: "_output"  
  resources: ".quarto/files"  # where figures and supporting files go

book:
  title: "Climate Classification Changes"
  subtitle: "Recent Period (2015–2024) vs WMO Climatological Reference Period (1961–1990)"
  author: "Rick Forest"
  date: today

  chapters:
    - index.qmd
    - 01_download_data.qmd
    - 02_aggregate_data.qmd
    - 03_derive_determinants.qmd
    - 04_assign_types.qmd
    - 05_analyze_changes.qmd

execute:
  freeze: auto
  cache: true
  cache-dir: .quarto/cache
  warning: false
  message: false

code-tools: true
code-fold: show

format:
  html:
    page-layout: full
    toc: true
    toc-location: right
    grid:
      sidebar-width: 200px
      body-width: 900px
      margin-width: 150px
      gutter-width: 1.5rem